# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker', models.CharField(max_length=100)),
                ('army', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ended', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResistenciaCoC.War'),
        ),
    ]
