# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResistenciaCoC', '0003_auto_20160123_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Castle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbarian_quantity', models.IntegerField()),
                ('barbarian_level', models.IntegerField()),
                ('archer_quantity', models.IntegerField()),
                ('archer_level', models.IntegerField()),
                ('giant_quantity', models.IntegerField()),
                ('giant_level', models.IntegerField()),
                ('goblin_quantity', models.IntegerField()),
                ('goblin_level', models.IntegerField()),
                ('wallbreaker_quantity', models.IntegerField()),
                ('wallbreaker_level', models.IntegerField()),
                ('balloon_quantity', models.IntegerField()),
                ('balloon_level', models.IntegerField()),
                ('wizard_quantity', models.IntegerField()),
                ('wizard_level', models.IntegerField()),
                ('healer_quantity', models.IntegerField()),
                ('healer_level', models.IntegerField()),
                ('dragon_quantity', models.IntegerField()),
                ('dragon_level', models.IntegerField()),
                ('pekka_quantity', models.IntegerField()),
                ('pekka_level', models.IntegerField()),
                ('minion_quantity', models.IntegerField()),
                ('minion_level', models.IntegerField()),
                ('hog_rider_quantity', models.IntegerField()),
                ('hog_rider_level', models.IntegerField()),
                ('valkyrie_quantity', models.IntegerField()),
                ('valkyrie_level', models.IntegerField()),
                ('golem_quantity', models.IntegerField()),
                ('golem_level', models.IntegerField()),
                ('witch_quantity', models.IntegerField()),
                ('witch_level', models.IntegerField()),
                ('lava_hound_quantity', models.IntegerField()),
                ('lava_hound_level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='attack',
            name='castle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ResistenciaCoC.Castle'),
        ),
    ]
