# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResistenciaCoC', '0004_auto_20160124_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='donor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
