# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResistenciaCoC', '0006_auto_20160126_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='castle',
            old_name='wallbreaker_max_needed',
            new_name='wall_breaker_max_needed',
        ),
        migrations.RenameField(
            model_name='castle',
            old_name='wallbreaker_quantity',
            new_name='wall_breaker_quantity',
        ),
    ]
