# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResistenciaCoC', '0008_clan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='name',
            field=models.CharField(default=' default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clan',
            name='tag',
            field=models.CharField(default='default', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
