# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResistenciaCoC', '0009_auto_20160131_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clan',
            old_name='manager',
            new_name='managers',
        ),
        migrations.RenameField(
            model_name='clan',
            old_name='member',
            new_name='members',
        ),
    ]
