# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResistenciaCoC', '0010_auto_20160201_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='is_at_war',
            field=models.BooleanField(default=False),
        ),
    ]
